version: "2.22"

networks:
  mynetwork:
    driver: bridge
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - mynetwork
    ports:
      - "27017:27017"

  tv_platform_backend:
    container_name: tv_platform_backend
    build:
      context: ./Back
      dockerfile: Dockerfile.Back
    networks:
      - mynetwork
    ports:
      - "9000:9000"
    environment:
      ACCESS_TOKEN_SECRET: 9cffa439-bbcf-4c62-8dde-48e54b2a6494
      REFRESH_TOKEN_SECRET: FreelanceSuiviClient*****
      PORT: 9000
      FRONTEND_ORIGIN: 80
      DB: mongodb://mongodb:27017/tv
      SALT: 10
      USERMAIL: chouroufarah1@gmail.com
      APP_PASSWORD: hiugejczdicsnull
      CLOUDINARY_NAME: duchnti5k
      CLOUDINARY_API_KEY: 981334676664949
      CLOUDINARY_API_SECRET: HKU0Sb3rm4gZLWGQyG_7QJI8zCk
    depends_on:
      - mongodb

  tv_platform_frontend:
    container_name: tv_platform_frontend
    build:
      context: ./Front
      dockerfile: Dockerfile.Front
    networks:
      - mynetwork
    ports:
      - "80:80"
    environment:
      REACT_APP_API_PORT: http://localhost:9000
    depends_on:
      - tv_platform_backend

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - tv_platform_backend

volumes:
  mongodb_data:
