# Use an official Node.js runtime as the base image
FROM node:18.14.2

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install project dependencies
RUN npm install -g nodemon
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

EXPOSE 8080

# Start the Node.js application
CMD ["npm", "start"]